from ldcorn.config import LdConfig, WorkerGroup

config = LdConfig(
    bind="127.0.0.1:8000",
    workers=[
        WorkerGroup(
            name="default",
            app="examples.app_block:app",
            instances=3,
            max_req_per_worker=0,
            routes=["*"],
            reload_on_sighup=False,
            uvicorn_log_level="error",
            max_restarts_on_crash=3,
            restart_backoff_on_crash=2
        ),
        WorkerGroup(
            name="ml",
            app="examples.app_block:app",
            instances=1,
            max_req_per_worker=0,
            routes=["/ml-pipeline"],
            reload_on_sighup=True,
            uvicorn_log_level="error",
            max_restarts_on_crash=3,
            restart_backoff_on_crash=2
        ),
        WorkerGroup(
            name="math",
            app="examples.app_block:app",
            instances=1,
            max_req_per_worker=0,
            routes=["/math"],
            reload_on_sighup=True,
            uvicorn_log_level="error",
            max_restarts_on_crash=3,
            restart_backoff_on_crash=2
        ),
        WorkerGroup(
            name="websocket_stateful",
            app="examples.app_block:app",
            instances=1,
            max_req_per_worker=0,
            routes=["/ws", "/counter"],
            reload_on_sighup=False,
            uvicorn_log_level="error",
            max_restarts_on_crash=3,
            restart_backoff_on_crash=2
        )
    ]
)
